import type { DashboardData } from './dashboard.types'

export const MOCK_DASHBOARD_DATA: Record<string, DashboardData> = {
  'EMP-01': {
    metrics: {
      totalLeads: 494,
      highPriorityLeads: 182,
      mediumPriorityLeads: 215,
      lowPriorityLeads: 97,
      unscoredLeads: 0,
      averageScore: 71.4,
      sampleSize: 494,
      isTotalCensus: true,
    },
    distributions: {
      priority: [
        { label: 'ALTA', value: 182, percentage: 36.8 },
        { label: 'MEDIA', value: 215, percentage: 43.5 },
        { label: 'BAJA', value: 97, percentage: 19.6 },
      ],
      channel: [
        { label: 'WHATSAPP', value: 248, percentage: 50.2 },
        { label: 'WEB', value: 132, percentage: 26.7 },
        { label: 'FACEBOOK_ADS', value: 78, percentage: 15.8 },
        { label: 'SHOWROOM', value: 36, percentage: 7.3 },
      ],
      managementStatus: [
        { label: 'EN_GESTION', value: 204, percentage: 41.3 },
        { label: 'NUEVO', value: 160, percentage: 32.4 },
        { label: 'CONTACTADO', value: 95, percentage: 19.2 },
        { label: 'CERRADO', value: 35, percentage: 7.1 },
      ],
      salesPoint: [
        { label: 'PV-01', value: 185, percentage: 37.5 },
        { label: 'PV-02', value: 164, percentage: 33.2 },
        { label: 'PV-03', value: 145, percentage: 29.3 },
      ],
    },
    salesPoints: [
      {
        companyId: 'EMP-01',
        salesPointId: 'PV-01',
        totalLeads: 185,
        highPriorityLeads: 74,
        averageScore: 73.8,
      },
      {
        companyId: 'EMP-01',
        salesPointId: 'PV-02',
        totalLeads: 164,
        highPriorityLeads: 61,
        averageScore: 70.9,
      },
      {
        companyId: 'EMP-01',
        salesPointId: 'PV-03',
        totalLeads: 145,
        highPriorityLeads: 47,
        averageScore: 69.1,
      },
    ],
    attentionLeads: [
      {
        id: 'LEAD-MOCK-001',
        customerName: 'Carlos Mario Giraldo',
        phoneMasked: '+57 310 *** 8921',
        salesPointId: 'PV-01',
        channel: 'WHATSAPP',
        modelInterest: 'Yamaha MT-03',
        score: 94.8,
        priorityTier: 'ALTA',
        conversionProbability: 0.88,
      },
      {
        id: 'LEAD-MOCK-002',
        customerName: 'Laura Marcela Builes',
        phoneMasked: '+57 320 *** 4410',
        salesPointId: 'PV-02',
        channel: 'WEB',
        modelInterest: 'KTM Duke 200 NG',
        score: 91.5,
        priorityTier: 'ALTA',
        conversionProbability: 0.83,
      },
      {
        id: 'LEAD-MOCK-003',
        customerName: 'Andrés Felipe Restrepo',
        phoneMasked: '+57 315 *** 7733',
        salesPointId: 'PV-01',
        channel: 'WHATSAPP',
        modelInterest: 'Bajaj Dominar 400',
        score: 88.2,
        priorityTier: 'ALTA',
        conversionProbability: 0.79,
      },
      {
        id: 'LEAD-MOCK-004',
        customerName: 'Valentina Osorio',
        phoneMasked: '+57 301 *** 1290',
        salesPointId: 'PV-03',
        channel: 'FACEBOOK_ADS',
        modelInterest: 'Suzuki Gixxer 250',
        score: 85.6,
        priorityTier: 'ALTA',
        conversionProbability: 0.75,
      },
      {
        id: 'LEAD-MOCK-005',
        customerName: 'Mateo Henao Castro',
        phoneMasked: '+57 318 *** 6542',
        salesPointId: 'PV-02',
        channel: 'WHATSAPP',
        modelInterest: 'Yamaha FZ 25',
        score: 83.1,
        priorityTier: 'ALTA',
        conversionProbability: 0.72,
      },
    ],
    metadata: {
      companyId: 'EMP-01',
      dataSource: 'mock',
      isDerived: false,
      sampleSize: 494,
      totalCompanyLeads: 494,
      syncTime: '10:30:00 p.m.',
      notice: 'Modo demostración (datos locales simulados para EMP-01).',
    },
  },
  'EMP-02': {
    metrics: {
      totalLeads: 513,
      highPriorityLeads: 165,
      mediumPriorityLeads: 230,
      lowPriorityLeads: 118,
      unscoredLeads: 0,
      averageScore: 68.9,
      sampleSize: 513,
      isTotalCensus: true,
    },
    distributions: {
      priority: [
        { label: 'ALTA', value: 165, percentage: 32.2 },
        { label: 'MEDIA', value: 230, percentage: 44.8 },
        { label: 'BAJA', value: 118, percentage: 23.0 },
      ],
      channel: [
        { label: 'WHATSAPP', value: 270, percentage: 52.6 },
        { label: 'WEB', value: 140, percentage: 27.3 },
        { label: 'FACEBOOK_ADS', value: 80, percentage: 15.6 },
        { label: 'SHOWROOM', value: 23, percentage: 4.5 },
      ],
      managementStatus: [
        { label: 'EN_GESTION', value: 220, percentage: 42.9 },
        { label: 'NUEVO', value: 175, percentage: 34.1 },
        { label: 'CONTACTADO', value: 88, percentage: 17.2 },
        { label: 'CERRADO', value: 30, percentage: 5.8 },
      ],
      salesPoint: [
        { label: 'PV-01', value: 280, percentage: 54.6 },
        { label: 'PV-02', value: 233, percentage: 45.4 },
      ],
    },
    salesPoints: [
      {
        companyId: 'EMP-02',
        salesPointId: 'PV-01',
        totalLeads: 280,
        highPriorityLeads: 95,
        averageScore: 71.1,
      },
      {
        companyId: 'EMP-02',
        salesPointId: 'PV-02',
        totalLeads: 233,
        highPriorityLeads: 70,
        averageScore: 66.4,
      },
    ],
    attentionLeads: [
      {
        id: 'LEAD-MOCK-021',
        customerName: 'Santiago Muñoz Vélez',
        phoneMasked: '+57 312 *** 5543',
        salesPointId: 'PV-01',
        channel: 'WHATSAPP',
        modelInterest: 'Pulsar NS 200 FI',
        score: 93.2,
        priorityTier: 'ALTA',
        conversionProbability: 0.85,
      },
      {
        id: 'LEAD-MOCK-022',
        customerName: 'Diana Patricia Londoño',
        phoneMasked: '+57 317 *** 9988',
        salesPointId: 'PV-01',
        channel: 'WEB',
        modelInterest: 'KTM Adventure 390',
        score: 89.4,
        priorityTier: 'ALTA',
        conversionProbability: 0.80,
      },
      {
        id: 'LEAD-MOCK-023',
        customerName: 'Jorge Eliecer Correa',
        phoneMasked: '+57 300 *** 6712',
        salesPointId: 'PV-02',
        channel: 'SHOWROOM',
        modelInterest: 'Yamaha NMAX 155',
        score: 86.0,
        priorityTier: 'ALTA',
        conversionProbability: 0.76,
      },
      {
        id: 'LEAD-MOCK-024',
        customerName: 'Camila Andrea Roldán',
        phoneMasked: '+57 314 *** 3321',
        salesPointId: 'PV-02',
        channel: 'WHATSAPP',
        modelInterest: 'Honda CB 190R',
        score: 82.5,
        priorityTier: 'ALTA',
        conversionProbability: 0.71,
      },
      {
        id: 'LEAD-MOCK-025',
        customerName: 'Esteban Ramírez',
        phoneMasked: '+57 311 *** 8009',
        salesPointId: 'PV-01',
        channel: 'WEB',
        modelInterest: 'Suzuki Gixxer 150',
        score: 80.7,
        priorityTier: 'ALTA',
        conversionProbability: 0.68,
      },
    ],
    metadata: {
      companyId: 'EMP-02',
      dataSource: 'mock',
      isDerived: false,
      sampleSize: 513,
      totalCompanyLeads: 513,
      syncTime: '10:30:00 p.m.',
      notice: 'Modo demostración (datos locales simulados para EMP-02).',
    },
  },
  'EMP-03': {
    metrics: {
      totalLeads: 493,
      highPriorityLeads: 158,
      mediumPriorityLeads: 219,
      lowPriorityLeads: 116,
      unscoredLeads: 0,
      averageScore: 69.8,
      sampleSize: 493,
      isTotalCensus: true,
    },
    distributions: {
      priority: [
        { label: 'ALTA', value: 158, percentage: 32.0 },
        { label: 'MEDIA', value: 219, percentage: 44.4 },
        { label: 'BAJA', value: 116, percentage: 23.5 },
      ],
      channel: [
        { label: 'WHATSAPP', value: 255, percentage: 51.7 },
        { label: 'WEB', value: 138, percentage: 28.0 },
        { label: 'FACEBOOK_ADS', value: 72, percentage: 14.6 },
        { label: 'SHOWROOM', value: 28, percentage: 5.7 },
      ],
      managementStatus: [
        { label: 'EN_GESTION', value: 212, percentage: 43.0 },
        { label: 'NUEVO', value: 158, percentage: 32.0 },
        { label: 'CONTACTADO', value: 91, percentage: 18.5 },
        { label: 'CERRADO', value: 32, percentage: 6.5 },
      ],
      salesPoint: [
        { label: 'PV-01', value: 258, percentage: 52.3 },
        { label: 'PV-02', value: 235, percentage: 47.7 },
      ],
    },
    salesPoints: [
      {
        companyId: 'EMP-03',
        salesPointId: 'PV-01',
        totalLeads: 258,
        highPriorityLeads: 88,
        averageScore: 71.5,
      },
      {
        companyId: 'EMP-03',
        salesPointId: 'PV-02',
        totalLeads: 235,
        highPriorityLeads: 70,
        averageScore: 68.0,
      },
    ],
    attentionLeads: [
      {
        id: 'LEAD-MOCK-031',
        customerName: 'Guillermo León Vélez',
        phoneMasked: '+57 319 *** 1122',
        salesPointId: 'PV-01',
        channel: 'WHATSAPP',
        modelInterest: 'Yamaha MT-07',
        score: 95.1,
        priorityTier: 'ALTA',
        conversionProbability: 0.89,
      },
      {
        id: 'LEAD-MOCK-032',
        customerName: 'Mariana Zuluaga',
        phoneMasked: '+57 313 *** 4433',
        salesPointId: 'PV-02',
        channel: 'WEB',
        modelInterest: 'KTM 250 Duke',
        score: 90.0,
        priorityTier: 'ALTA',
        conversionProbability: 0.81,
      },
      {
        id: 'LEAD-MOCK-033',
        customerName: 'David Alejandro Ríos',
        phoneMasked: '+57 316 *** 9900',
        salesPointId: 'PV-01',
        channel: 'WHATSAPP',
        modelInterest: 'Bajaj Pulsar N250',
        score: 87.3,
        priorityTier: 'ALTA',
        conversionProbability: 0.77,
      },
      {
        id: 'LEAD-MOCK-034',
        customerName: 'Paula Andrea Tabares',
        phoneMasked: '+57 302 *** 8877',
        salesPointId: 'PV-02',
        channel: 'FACEBOOK_ADS',
        modelInterest: 'Suzuki DR 150',
        score: 84.2,
        priorityTier: 'ALTA',
        conversionProbability: 0.73,
      },
      {
        id: 'LEAD-MOCK-035',
        customerName: 'Felipe Jaramillo',
        phoneMasked: '+57 310 *** 5566',
        salesPointId: 'PV-01',
        channel: 'SHOWROOM',
        modelInterest: 'Yamaha Crypton FI',
        score: 81.9,
        priorityTier: 'ALTA',
        conversionProbability: 0.70,
      },
    ],
    metadata: {
      companyId: 'EMP-03',
      dataSource: 'mock',
      isDerived: false,
      sampleSize: 493,
      totalCompanyLeads: 493,
      syncTime: '10:30:00 p.m.',
      notice: 'Modo demostración (datos locales simulados para EMP-03).',
    },
  },
}
