"""add_historical_closings_and_scoring

Revision ID: 0b9369195344
Revises: 83d3f87eeb14
Create Date: 2026-09-17 07:47:30.655483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b9369195344'
down_revision: Union[str, Sequence[str], None] = '83d3f87eeb14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_closings',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('company_id', sa.String(length=20), nullable=False),
    sa.Column('sales_point_id', sa.String(length=20), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('quoted_model', sa.String(length=150), nullable=True),
    sa.Column('list_price', sa.BigInteger(), nullable=True),
    sa.Column('hours_to_first_contact', sa.Float(), nullable=True),
    sa.Column('contact_count', sa.Integer(), nullable=True),
    sa.Column('down_payment_manifested', sa.String(length=50), nullable=True),
    sa.Column('declared_payment_method', sa.String(length=50), nullable=True),
    sa.Column('requested_appointment', sa.Boolean(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_point_id', 'company_id'], ['sales_points.id', 'sales_points.company_id'], name='fk_historical_closings_sales_point_company', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_closings_company_id'), 'historical_closings', ['company_id'], unique=False)
    op.create_index(op.f('ix_historical_closings_outcome'), 'historical_closings', ['outcome'], unique=False)
    op.create_table('lead_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.String(length=20), nullable=False),
    sa.Column('company_id', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('priority_tier', sa.String(length=20), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id', name='uq_lead_scores_lead_id')
    )
    op.create_index(op.f('ix_lead_scores_company_id'), 'lead_scores', ['company_id'], unique=False)
    op.create_index('ix_lead_scores_company_score', 'lead_scores', ['company_id', 'score'], unique=False)
    op.create_index('ix_lead_scores_company_tier', 'lead_scores', ['company_id', 'priority_tier'], unique=False)
    op.create_index(op.f('ix_lead_scores_lead_id'), 'lead_scores', ['lead_id'], unique=False)
    op.create_table('conversation_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.String(length=20), nullable=False),
    sa.Column('lead_id', sa.String(length=20), nullable=True),
    sa.Column('company_id', sa.String(length=20), nullable=False),
    sa.Column('purchase_intent_score', sa.Float(), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('down_payment_declared', sa.Boolean(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('appointment_requested', sa.Boolean(), nullable=False),
    sa.Column('model_detected', sa.String(length=150), nullable=True),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_analyses_company_id'), 'conversation_analyses', ['company_id'], unique=False)
    op.create_index(op.f('ix_conversation_analyses_conversation_id'), 'conversation_analyses', ['conversation_id'], unique=True)
    op.create_index(op.f('ix_conversation_analyses_lead_id'), 'conversation_analyses', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_analyses_lead_id'), table_name='conversation_analyses')
    op.drop_index(op.f('ix_conversation_analyses_conversation_id'), table_name='conversation_analyses')
    op.drop_index(op.f('ix_conversation_analyses_company_id'), table_name='conversation_analyses')
    op.drop_table('conversation_analyses')
    op.drop_index(op.f('ix_lead_scores_lead_id'), table_name='lead_scores')
    op.drop_index('ix_lead_scores_company_tier', table_name='lead_scores')
    op.drop_index('ix_lead_scores_company_score', table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_company_id'), table_name='lead_scores')
    op.drop_table('lead_scores')
    op.drop_index(op.f('ix_historical_closings_outcome'), table_name='historical_closings')
    op.drop_index(op.f('ix_historical_closings_company_id'), table_name='historical_closings')
    op.drop_table('historical_closings')
    # ### end Alembic commands ###
