"""add_historical_closings_audit_and_targets

Revision ID: 48102b1244e8
Revises: 0b9369195344
Create Date: 2026-09-17 10:15:28.356934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48102b1244e8'
down_revision: Union[str, Sequence[str], None] = '0b9369195344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historical_closings', sa.Column('channel_raw', sa.String(length=50), nullable=True))
    op.add_column('historical_closings', sa.Column('down_payment_raw', sa.String(length=50), nullable=True))
    op.add_column('historical_closings', sa.Column('declared_payment_method_raw', sa.String(length=50), nullable=True))
    op.add_column('historical_closings', sa.Column('requested_appointment_raw', sa.String(length=50), nullable=True))
    op.add_column('historical_closings', sa.Column('outcome_raw', sa.String(length=50), nullable=True))
    op.add_column('historical_closings', sa.Column('target_converted', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_historical_closings_target_converted'), 'historical_closings', ['target_converted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historical_closings_target_converted'), table_name='historical_closings')
    op.drop_column('historical_closings', 'target_converted')
    op.drop_column('historical_closings', 'outcome_raw')
    op.drop_column('historical_closings', 'requested_appointment_raw')
    op.drop_column('historical_closings', 'declared_payment_method_raw')
    op.drop_column('historical_closings', 'down_payment_raw')
    op.drop_column('historical_closings', 'channel_raw')
    # ### end Alembic commands ###
