"""create motorcycle catalog and availability tables

Revision ID: 9880fba94db4
Revises: add046ffe8de
Create Date: 2026-09-16 22:21:48.834316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9880fba94db4'
down_revision: Union[str, Sequence[str], None] = 'add046ffe8de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motorcycles',
    sa.Column('sku', sa.String(length=20), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('line', sa.String(length=150), nullable=False),
    sa.Column('engine_displacement_cc', sa.Integer(), nullable=False),
    sa.Column('segment', sa.String(length=100), nullable=False),
    sa.Column('list_price', sa.BigInteger(), nullable=False),
    sa.Column('reported_available_units', sa.Integer(), nullable=False),
    sa.CheckConstraint('engine_displacement_cc > 0', name='ck_motorcycles_engine_displacement_positive'),
    sa.CheckConstraint('list_price > 0', name='ck_motorcycles_list_price_positive'),
    sa.CheckConstraint('reported_available_units >= 0', name='ck_motorcycles_reported_available_units_non_negative'),
    sa.PrimaryKeyConstraint('sku')
    )
    op.create_table('motorcycle_availability',
    sa.Column('motorcycle_sku', sa.String(length=20), nullable=False),
    sa.Column('sales_point_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['motorcycle_sku'], ['motorcycles.sku'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_point_id'], ['sales_points.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('motorcycle_sku', 'sales_point_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motorcycle_availability')
    op.drop_table('motorcycles')
    # ### end Alembic commands ###
