"""create organization and advisors tables

Revision ID: add046ffe8de
Revises: 2e45d311890f
Create Date: 2026-09-16 22:11:42.337759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add046ffe8de'
down_revision: Union[str, Sequence[str], None] = '2e45d311890f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_points',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('company_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'company_id', name='uq_sales_points_id_company')
    )
    op.create_index(op.f('ix_sales_points_company_id'), 'sales_points', ['company_id'], unique=False)
    op.create_table('advisors',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('sales_point_id', sa.String(length=20), nullable=False),
    sa.Column('company_id', sa.String(length=20), nullable=False),
    sa.Column('daily_lead_capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hired_at', sa.Date(), nullable=False),
    sa.CheckConstraint('daily_lead_capacity > 0', name='ck_advisors_daily_lead_capacity_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_point_id', 'company_id'], ['sales_points.id', 'sales_points.company_id'], name='fk_advisors_sales_point_company', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advisors_company_id'), 'advisors', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advisors_company_id'), table_name='advisors')
    op.drop_table('advisors')
    op.drop_index(op.f('ix_sales_points_company_id'), table_name='sales_points')
    op.drop_table('sales_points')
    op.drop_table('companies')
    # ### end Alembic commands ###
