"""create_pipeline_step_runs_table

Revision ID: d86fa0c206d1
Revises: aa5eafac932b
Create Date: 2026-09-17 12:01:11.645862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd86fa0c206d1'
down_revision: Union[str, Sequence[str], None] = 'aa5eafac932b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_step_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=False),
    sa.Column('step_name', sa.String(length=50), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_received', sa.Integer(), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_rejected', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('step_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_step_runs_pipeline_run_id'), 'pipeline_step_runs', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_pipeline_step_runs_step_name'), 'pipeline_step_runs', ['step_name'], unique=False)
    op.alter_column('lead_duplicate_candidates', 'company_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_lead_duplicate_candidates_confidence_tier'), 'lead_duplicate_candidates', ['confidence_tier'], unique=False)
    op.create_index(op.f('ix_lead_duplicate_candidates_status'), 'lead_duplicate_candidates', ['status'], unique=False)
    op.alter_column('scoring_runs', 'company_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scoring_runs', 'company_id',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_index(op.f('ix_lead_duplicate_candidates_status'), table_name='lead_duplicate_candidates')
    op.drop_index(op.f('ix_lead_duplicate_candidates_confidence_tier'), table_name='lead_duplicate_candidates')
    op.alter_column('lead_duplicate_candidates', 'company_id',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_index(op.f('ix_pipeline_step_runs_step_name'), table_name='pipeline_step_runs')
    op.drop_index(op.f('ix_pipeline_step_runs_pipeline_run_id'), table_name='pipeline_step_runs')
    op.drop_table('pipeline_step_runs')
    # ### end Alembic commands ###
