"""create leads and source records tables

Revision ID: e665a39465e5
Revises: 9880fba94db4
Create Date: 2026-09-16 22:30:22.371046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e665a39465e5'
down_revision: Union[str, Sequence[str], None] = '9880fba94db4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('company_id', sa.String(length=20), nullable=False),
    sa.Column('sales_point_id', sa.String(length=20), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('phone_raw', sa.String(length=50), nullable=True),
    sa.Column('phone_normalized', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('model_interest_text', sa.Text(), nullable=True),
    sa.Column('management_status', sa.String(length=100), nullable=True),
    sa.Column('first_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('campaign', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_point_id', 'company_id'], ['sales_points.id', 'sales_points.company_id'], name='fk_leads_sales_point_company', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_company_id'), 'leads', ['company_id'], unique=False)
    op.create_index(op.f('ix_leads_phone_normalized'), 'leads', ['phone_normalized'], unique=False)
    op.create_table('lead_source_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.String(length=20), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('source_lead_id', sa.String(length=20), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_file', 'source_row_number', name='uq_lead_source_records_file_row')
    )
    op.create_index(op.f('ix_lead_source_records_lead_id'), 'lead_source_records', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_source_records_source_lead_id'), 'lead_source_records', ['source_lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_source_records_source_lead_id'), table_name='lead_source_records')
    op.drop_index(op.f('ix_lead_source_records_lead_id'), table_name='lead_source_records')
    op.drop_table('lead_source_records')
    op.drop_index(op.f('ix_leads_phone_normalized'), table_name='leads')
    op.drop_index(op.f('ix_leads_company_id'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
