import type { PrioritizedLead } from './lead.types'

/**
 * Datos mock explícitos y locales para el listado de leads priorizados.
 * Solo utiliza compañías EMP-01, EMP-02 y EMP-03, IDs LD-xxxxx y puntos de venta PV-xxx.
 * Los scores son valores simulados para validar la interfaz sin depender del backend.
 */
export const MOCK_PRIORITIZED_LEADS: PrioritizedLead[] = [
  {
    id: 'LD-00101',
    companyId: 'EMP-01',
    salesPointId: 'PV-001',
    customerName: 'Carlos Mendoza',
    channel: 'WhatsApp',
    managementStatus: 'Nuevo',
    modelInterestText: 'Yamaha MT-03',
    registeredAt: '2026-09-17T14:30:00Z',
    priority: 'high',
    score: 95,
  },
  {
    id: 'LD-00102',
    companyId: 'EMP-01',
    salesPointId: 'PV-001',
    customerName: 'Mariana Gómez',
    channel: 'Meta Ads',
    managementStatus: 'Contactado',
    modelInterestText: 'KTM 390 Duke',
    registeredAt: '2026-09-17T13:15:00Z',
    priority: 'high',
    score: 91,
  },
  {
    id: 'LD-00103',
    companyId: 'EMP-02',
    salesPointId: 'PV-002',
    customerName: 'Jorge Silva',
    channel: 'Formulario web',
    managementStatus: 'En gestión',
    modelInterestText: 'Bajaj Pulsar NS 200 FI',
    registeredAt: '2026-09-17T11:45:00Z',
    priority: 'medium',
    score: 74,
  },
  {
    id: 'LD-00104',
    companyId: 'EMP-01',
    salesPointId: 'PV-001',
    customerName: 'Santiago Morales',
    channel: 'WhatsApp',
    managementStatus: 'Calificado',
    modelInterestText: 'Kawasaki Ninja 400',
    registeredAt: '2026-09-17T10:20:00Z',
    priority: 'high',
    score: 88,
  },
  {
    id: 'LD-00105',
    companyId: 'EMP-03',
    salesPointId: 'PV-003',
    customerName: 'Laura Castro',
    channel: 'Meta Ads',
    managementStatus: 'Nuevo',
    modelInterestText: 'Suzuki Gixxer 150 FI',
    registeredAt: '2026-09-17T09:05:00Z',
    priority: 'medium',
    score: 68,
  },
  {
    id: 'LD-00106',
    companyId: 'EMP-02',
    salesPointId: 'PV-002',
    customerName: 'Andrea Torres',
    channel: 'Formulario web',
    managementStatus: 'Descartado',
    modelInterestText: 'Honda CB 190R',
    registeredAt: '2026-09-16T18:20:00Z',
    priority: 'low',
    score: 35,
  },
  {
    id: 'LD-00107',
    companyId: 'EMP-01',
    salesPointId: 'PV-001',
    customerName: 'Felipe Restrepo',
    channel: 'WhatsApp',
    managementStatus: 'En gestión',
    modelInterestText: 'Yamaha NMAX 155',
    registeredAt: '2026-09-16T16:50:00Z',
    priority: 'high',
    score: 84,
  },
  {
    id: 'LD-00108',
    companyId: 'EMP-03',
    salesPointId: 'PV-003',
    customerName: 'Valentina Rios',
    channel: 'Meta Ads',
    managementStatus: 'Contactado',
    modelInterestText: 'Bajaj Dominar 400',
    registeredAt: '2026-09-16T15:10:00Z',
    priority: 'medium',
    score: 72,
  },
  {
    id: 'LD-00109',
    companyId: 'EMP-02',
    salesPointId: 'PV-002',
    customerName: 'David Henao',
    channel: 'Formulario web',
    managementStatus: 'Nuevo',
    modelInterestText: 'Suzuki V-Strom 250 SX',
    registeredAt: '2026-09-16T12:00:00Z',
    priority: 'medium',
    score: 63,
  },
  {
    id: 'LD-00110',
    companyId: 'EMP-01',
    salesPointId: 'PV-001',
    customerName: 'Camila Zapata',
    channel: 'WhatsApp',
    managementStatus: 'Calificado',
    modelInterestText: 'KTM 250 Duke',
    registeredAt: '2026-09-16T10:30:00Z',
    priority: 'high',
    score: 89,
  },
  {
    id: 'LD-00111',
    companyId: 'EMP-02',
    salesPointId: 'PV-002',
    customerName: 'Alejandro Ospina',
    channel: 'Meta Ads',
    managementStatus: 'Nuevo',
    modelInterestText: 'Honda XR 190L',
    registeredAt: '2026-09-15T19:40:00Z',
    priority: 'low',
    score: 48,
  },
  {
    id: 'LD-00112',
    companyId: 'EMP-03',
    salesPointId: 'PV-003',
    customerName: 'Natalia Pelaez',
    channel: 'Formulario web',
    managementStatus: 'Contactado',
    modelInterestText: 'Yamaha FZ-25',
    registeredAt: '2026-09-15T17:15:00Z',
    priority: 'low',
    score: null, // Caso especial: lead recién recibido sin score calculado
  },
  {
    id: 'LD-00113',
    companyId: 'EMP-01',
    salesPointId: 'PV-001',
    customerName: 'Esteban Valencia',
    channel: 'WhatsApp',
    managementStatus: 'En gestión',
    modelInterestText: 'Kawasaki Z400',
    registeredAt: '2026-09-15T14:00:00Z',
    priority: 'high',
    score: 86,
  },
  {
    id: 'LD-00114',
    companyId: 'EMP-02',
    salesPointId: 'PV-002',
    customerName: 'Daniela Cardona',
    channel: 'Meta Ads',
    managementStatus: 'Nuevo',
    modelInterestText: 'Bajaj Pulsar N250',
    registeredAt: '2026-09-15T11:20:00Z',
    priority: 'medium',
    score: 65,
  },
  {
    id: 'LD-00115',
    companyId: 'EMP-03',
    salesPointId: 'PV-003',
    customerName: 'Mateo Arango',
    channel: 'Formulario web',
    managementStatus: 'Descartado',
    modelInterestText: 'TVS Apache RTR 200',
    registeredAt: '2026-09-14T16:30:00Z',
    priority: 'low',
    score: 28,
  },
  {
    id: 'LD-00116',
    companyId: 'EMP-01',
    salesPointId: 'PV-001',
    customerName: 'Juliana Munera',
    channel: 'WhatsApp',
    managementStatus: 'Calificado',
    modelInterestText: 'Yamaha MT-03',
    registeredAt: '2026-09-14T13:10:00Z',
    priority: 'high',
    score: 93,
  },
]
